version: "3.8"
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "8001:8001"
    networks: 
     - network-backend
  
  mongo:
    image: mongo:latest
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: ousmane
      MONGODB_INITDB_ROOT_PASSWORD: ousmane
    # uncomment following lines to access db locally
    # ports:
    #   - 80007:80007
    networks: 
     - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
