version: "3.8"  

services:
  web:
    build: ./frontend  
    depends_on:
      - api 
    ports:    
      - "8022:80"
    networks:
      - network
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "8099:8080"
    networks: 
     - network-backend
  
  mongo:
    image: mongo:latest
    restart: always
    volumes: 
      - mongodb_data: /database/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: ousmane
      MONGODB_INITDB_ROOT_PASSWORD: ousmane
    # uncomment following lines to access db locally
    ports:
     - "80007:80007"
    networks: 
     - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data: /database/mango/mangodb_data
